# Candidates per page
PageSize=5
# 힌트에 이모지 표시
EnableEmoji=True
# 상용구에 이모지 사용
EnableQuickPhraseEmoji=True
# 변환 키 선택
Choose Modifier=Alt
# 기본적으로 힌트 활성화
EnableHintByDefault=False
# 힌트 모드 실행
Hint Trigger=
# 한 번만 힌트 모드 실행
One Time Hint Trigger=
# 새 조합 동작 사용
UseNewComposeBehavior=True
# 길게 눌러 특수 문자 입력
EnableLongPress=False

[PrevCandidate]
0=Shift+Tab

[NextCandidate]
0=Tab

[LongPressBlocklist]
0=konsole
1=org.kde.konsole

