#!/usr/bin/env bash

if [[ $JUPCID == "HOME-DESKTOP" ]]; then
    xrandr --output DP-0 --primary --mode 3840x2160 --rotate normal --output HDMI-0 --mode 1920x1080 --rotate right --right-of DP-0 --output DP-2 --mode 2560x1440 --left-of DP-0
elif [[ $JUPCID == "HSCDEV" ]]; then
    xrandr --output HDMI-1 --primary --mode 2560x1440 --rotate normal
fi
##################################################
# AUTOSTART
##################################################
sleep 1
killall sxhkd
killall picom
killall fcitx5
killall nm-applet
killall volumeicon
sxhkd &
picom &
fcitx5 -d &
nm-applet &
volumeicon &
#killall conky
#sleep 3 && conky -c ~/.config/conky/conkyrc
emacsclient --eval '(kill-emacs)'
emacs --daemon

~/scripts/random_wallpaper.sh

wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

if [[ $JUPCID == "HOME-DESKTOP" ]]; then
    bspc monitor DP-0 -d 1 2 3 4 5
    bspc monitor DP-2 -d 6 7 8 9
    bspc monitor HDMI-0 -d 0
elif [[ $JUPCID == "HSCDEV" ]]; then
    bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 20
bspc config border_radius 2
bspc config focus_follows_pointer true
#bspc config click_to_focus				true
bspc config gapless_monocle true
#bspc config pointer_follows_focus       true
#bspc config single_monocle              true
bspc config top_monocle_padding 20
bspc config left_monocle_padding 20
bspc config right_monocle_padding 20
bspc config bottom_monocle_padding 20
#bspc config ignore_ewmh_fullscreen       enter

# Colors
bspc config focused_border_color "$color9"
bspc config active_border_color "$color9"
bspc config normal_border_color "$color1"
bspc config urgent_border_color "$color1"
bspc config presel_feedback_color "$color1"
bspc config focused_locked_border_color "$color1"
bspc config active_locked_border_color "$color1"
bspc config normal_locked_border_color "$color1"
bspc config focused_sticky_border_color "$color1"
bspc config active_sticky_border_color "$color1"
bspc config normal_sticky_border_color "$color1"
bspc config focused_private_border_color "$color1"
bspc config active_private_border_color "$color1"
bspc config normal_private_border_color "$color1"

bspc rule -a Emacs state=tiled
# bspc rule -a \* state=tiled
if [[ $JUPCID == "HOME-DESKTOP" ]]; then
    bspc rule -a scpad sticky=on state=floating rectangle=1400x700+1220+730
    bspc rule -a pythonpad sticky=on state=floating rectangle=1400x700+1220+730
elif [[ $JUPCID == "HSCDEV" ]]; then
    bspc rule -a scpad sticky=on state=floating rectangle=1400x700+580+370
    bspc rule -a pythonpad sticky=on state=floating rectangle=1400x700+580+370
fi

if [[ $JUPCID == "HOME-DESKTOP" ]]; then
    polybar panel-bspwm-1 &
    polybar panel-bspwm-2 &
    polybar panel-bspwm-3 &
elif [[ $JUPCID == "HSCDEV" ]]; then
    polybar panel-bspwm &
fi

# Theme
#xsettingsd --config="$HOME/.config/bspwm/xsettingsd" &
