#!/usr/bin/env bash

source ~/.profile

if [[ $JUPCID == "HOME-DESKTOP" ]]; then
    xrandr --output DP-4 --primary --mode 2560x1440 --rotate normal --output HDMI-0 --rotate right --right-of DP-4
elif [[ $JUPCID == "HWDEV" ]]; then
    xrandr --output HDMI-1 --primary --mode 2560x1440 --rotate normal
fi

killall bspc

##################################################
# AUTOSTART
##################################################
sleep 1
killall sxhkd
killall picom
sxhkd &
picom &
killall nm-applet && nm-applet &
killall volumeicon && volumeicon &
#killall conky
#sleep 3 && conky -c ~/.config/conky/conkyrc
emacsclient --eval '(kill-emacs)'
emacs --daemon

~/scripts/random_wallpaper.sh

wmname LG3D
export _JAVA_AWT_WM_NONREPARETING=1

if [[ $JUPCID == "HOME-DESKTOP" ]]; then
    bspc monitor DP-4 -d 1 2 3 4 5
    bspc monitor HDMI-0 -d 6 7 8 9 0
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config border_width        2
bspc config window_gap          10
bspc config top_padding         20
bspc config border_radius       2
bspc config focus_follows_pointer       true
#bspc config click_to_focus				true
bspc config gapless_monocle             true
#bspc config pointer_follows_focus       true
#bspc config single_monocle              true
bspc config top_monocle_padding          20
bspc config left_monocle_padding         20
bspc config right_monocle_padding        20
bspc config bottom_monocle_padding       20
#bspc config ignore_ewmh_fullscreen       enter

# Colors
bspc config focused_border_color            "$color9"
bspc config active_border_color             "$color9"
bspc config normal_border_color             "$color1"
bspc config urgent_border_color             "$color1"
bspc config presel_feedback_color           "$color1"
bspc config focused_locked_border_color     "$color1"
bspc config active_locked_border_color      "$color1"
bspc config normal_locked_border_color      "$color1"
bspc config focused_sticky_border_color     "$color1"
bspc config active_sticky_border_color      "$color1"
bspc config normal_sticky_border_color      "$color1"
bspc config focused_private_border_color    "$color1"
bspc config active_private_border_color     "$color1"
bspc config normal_private_border_color     "$color1"

bspc rule -a Emacs state=tiled
# bspc rule -a \* state=tiled
bspc rule -a scpad sticky=on state=floating rectangle=1400x600+660+40

# TODO heres polybar
if [[ $JUPCID == "HOME-DESKTOP" ]]; then
    polybar panel-bspwm-1 & polybar panel-bspwm-2
else
    polybar panel-bspwm --config=~/.config/polybar/config.ini
fi
