#!/bin/bash

export JUPCID=HOME-DESKTOP
# Set environment variables
export PATH="$HOME/scripts:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
export QT_QPA_PLATFORMTHEME=kde
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

if [[ $JUPCID == "HOME-DESKTOP" ]]; then
    xrandr --output DP-0 --primary --mode 3840x2160 --rotate normal --output HDMI-0 --mode 1920x1080 --rotate right --right-of DP-0 --output DP-2 --mode 2560x1440 --left-of DP-0
elif [[ $JUPCID == "HSCDEV" ]]; then
    xrandr --output HDMI-1 --primary --mode 2560x1440 --rotate normal
fi
xsetroot -cursor_name left_ptr

##################################################
# AUTOSTART
##################################################
sleep 1
killall sxhkd
killall picom
killall fcitx5
killall polybar
killall xsettingsd
sxhkd &
picom &
fcitx5 -d &
export KDE_FULL_SESSION=true
export KDE_SESSION_VERSION=6
dbus-update-activation-environment --systemd KDE_FULL_SESSION KDE_SESSION_VERSION 2>/dev/null
kwalletd6 &
/usr/lib/pam_kwallet_init &
/usr/lib/polkit-kde-authentication-agent-1 &
#killall conky
#sleep 3 && conky -c ~/.config/conky/conkyrc
emacsclient --eval '(kill-emacs)'
emacs --daemon
xsettingsd --config="$HOME/.config/bspwm/xsettingsd" &

~/scripts/random_wallpaper.sh

wmname LG3D

if [[ $JUPCID == "HOME-DESKTOP" ]]; then
    bspc monitor DP-0 -d 1 2 3 4 5
    bspc monitor DP-2 -d 6 7 8 9
    bspc monitor HDMI-0 -d 0
elif [[ $JUPCID == "HSCDEV" ]]; then
    bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 23
bspc config border_radius 2
bspc config focus_follows_pointer true
#bspc config click_to_focus				true
bspc config gapless_monocle true
bspc config pointer_follows_focus       false
#bspc config single_monocle              true
bspc config top_monocle_padding 20
bspc config left_monocle_padding 20
bspc config right_monocle_padding 20
bspc config bottom_monocle_padding 20
#bspc config ignore_ewmh_fullscreen       enter

# Colors (pywal)
[ -f "$HOME/.cache/wal/colors.sh" ] && source "$HOME/.cache/wal/colors.sh"

bspc config focused_border_color        "$color4"
bspc config active_border_color         "$color8"
bspc config normal_border_color         "$color0"
bspc config urgent_border_color         "$color1"
bspc config presel_feedback_color       "$color4"
bspc config focused_locked_border_color "$color8"
bspc config active_locked_border_color  "$color8"
bspc config normal_locked_border_color  "$color0"
bspc config focused_sticky_border_color "$color8"
bspc config active_sticky_border_color  "$color8"
bspc config normal_sticky_border_color  "$color0"
bspc config focused_private_border_color "$color8"
bspc config active_private_border_color  "$color8"
bspc config normal_private_border_color  "$color0"

bspc rule -a Emacs state=tiled
bspc rule -a pavucontrol state=floating
# bspc rule -a \* state=tiled

for mon in $(polybar --list-monitors | cut -d":" -f1); do
    dims=$(xrandr | grep "^$mon connected" | grep -oP '\d+x\d+(?=\+)' | head -1)
    w=$(echo "$dims" | cut -dx -f1)
    h=$(echo "$dims" | cut -dx -f2)
    size=$(( w > h ? w : h ))
    if [[ $size -ge 3840 ]]; then
        bar="marisol-4k"; pad=47
    elif [[ $size -ge 2560 ]]; then
        bar="marisol-qhd"; pad=31
    else
        bar="marisol-fhd"; pad=23
    fi
    bspc config -m "$mon" top_padding $pad
    MONITOR=$mon polybar -q $bar -c "$HOME/.config/polybar/config.ini" &
done

# Theme
