#!/usr/bin/env bash

winclass="$(xdotool search --class pythonpad)";

if [ -z "$winclass" ]; then
    PYTHONSTARTUP=/home/jaeus/scripts/my_imports.py alacritty --class pythonpad -e python
else
    if [ ! -f /tmp/pythonpad ]; then
        touch /tmp/pythonpad && xdo hide "$winclass"
    elif [ -f /tmp/pythonpad ]; then
        rm /tmp/pythonpad && xdo show "$winclass"
    fi
fi





